version: '3'
services:
  startemailapp:
    restart: unless-stopped
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - startemailapp-mysql
      - startemailapp-redis

  startemailapp-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: unless-stopped
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: startemailapp
      MYSQL_ROOT_PASSWORD: root

  startemailapp-nginx:
    build: ./.docker/nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    depends_on:
      - startemailapp

  startemailapp-redis:
    image: redis:alpine
    expose:
      - 6379

networks:
  default:
    external:
      name: takeaway-network
